//! Auto-generated client for the oracle_prices program.
//! Generated by spel-client-gen from IDL v0.1.0.
//! DO NOT EDIT — regenerate from IDL instead.

use sequencer_service_rpc::RpcClient as _;
use nssa::{
    AccountId, ProgramId, PublicTransaction,
    public_transaction::{Message, WitnessSet},
};
use borsh::BorshDeserialize;
use serde::{Deserialize, Serialize};
use wallet::WalletCore;

/// Parse a hex string into ProgramId [u32; 8] (little-endian byte order).
pub fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {
    let s = s.trim_start_matches("0x");
    if s.len() != 64 {
        return Err(format!("program_id hex must be 64 chars, got {}", s.len()));
    }
    let bytes = hex::decode(s).map_err(|e| format!("invalid hex: {}", e))?;
    let mut pid = [0u32; 8];
    for (i, chunk) in bytes.chunks(4).enumerate() {
        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());
    }
    Ok(pid)
}

/// Compute PDA for the `oracle_prices_account` account.
pub fn compute_oracle_prices_account_pda(program_id: &ProgramId) -> AccountId {
    let seed_const_0 = spel_framework_core::pda::seed_from_str("oracle_prices");
    spel_framework_core::pda::compute_pda(program_id, &[
        &seed_const_0,
    ])
}

/// Compute PDA for the `feed_price` account.
pub fn compute_feed_price_pda(program_id: &ProgramId, feed_id: &[u8; 32]) -> AccountId {
    let seed_const_0 = spel_framework_core::pda::seed_from_str("oracle_prices__");
    spel_framework_core::pda::compute_pda(program_id, &[
        &seed_const_0,
        feed_id,
    ])
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum OraclePricesInstruction {
    Initialize,
    InitializeFeed {
        feed_id: [u8; 32],
    },
    PublishPrice {
        feed_id: [u8; 32],
        price: u64,
        decimals: u32,
        valid_count: u32,
        round: u64,
        confidence: u64,
    },
}

pub struct InitializeAccounts {
    pub oracle_prices_account: AccountId,
}

pub struct InitializeFeedAccounts {
    pub oracle_prices_account: AccountId,
    pub feed_price: AccountId,
}

pub struct PublishPriceAccounts {
    pub feed_price: AccountId,
}


pub struct OraclePricesClient<'w> {
    pub wallet: &'w WalletCore,
    pub program_id: ProgramId,
}

impl<'w> OraclePricesClient<'w> {
    pub fn new(wallet: &'w WalletCore, program_id: ProgramId) -> Self {
        Self { wallet, program_id }
    }

    pub async fn initialize(
        &self,
        accounts: InitializeAccounts,
    ) -> Result<String, String> {
        let instruction = OraclePricesInstruction::Initialize;
        let mut account_ids: Vec<AccountId> = vec![
            accounts.oracle_prices_account,
        ];
        let signer_ids: Vec<AccountId> = vec![
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    pub async fn initialize_feed(
        &self,
        accounts: InitializeFeedAccounts,
        feed_id: [u8; 32],
    ) -> Result<String, String> {
        let instruction = OraclePricesInstruction::InitializeFeed {
            feed_id,
        };
        let mut account_ids: Vec<AccountId> = vec![
            accounts.oracle_prices_account,
            accounts.feed_price,
        ];
        let signer_ids: Vec<AccountId> = vec![
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    pub async fn publish_price(
        &self,
        accounts: PublishPriceAccounts,
        feed_id: [u8; 32],
        price: u64,
        decimals: u32,
        valid_count: u32,
        round: u64,
        confidence: u64,
    ) -> Result<String, String> {
        let instruction = OraclePricesInstruction::PublishPrice {
            feed_id,
            price,
            decimals,
            valid_count,
            round,
            confidence,
        };
        let mut account_ids: Vec<AccountId> = vec![
            accounts.feed_price,
        ];
        let signer_ids: Vec<AccountId> = vec![
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    /// Fetch and deserialize the `oracle_prices_account` account state.
    pub async fn fetch_oracle_prices_account<T: BorshDeserialize>(
        &self,
    ) -> Result<T, String> {
        let account_id = compute_oracle_prices_account_pda(&self.program_id);
        let account = self.wallet.sequencer_client
            .get_account(account_id).await
            .map_err(|e| format!("fetch oracle_prices_account: {}", e))?;
        T::try_from_slice(&account.data)
            .map_err(|e| format!("deserialize oracle_prices_account: {}", e))
    }

    /// Fetch and deserialize the `feed_price` account state.
    pub async fn fetch_feed_price<T: BorshDeserialize>(
        &self,
        feed_id: &[u8; 32],
    ) -> Result<T, String> {
        let account_id = compute_feed_price_pda(&self.program_id, feed_id);
        let account = self.wallet.sequencer_client
            .get_account(account_id).await
            .map_err(|e| format!("fetch feed_price: {}", e))?;
        T::try_from_slice(&account.data)
            .map_err(|e| format!("deserialize feed_price: {}", e))
    }
}
