//! Auto-generated client for the my_counter program.
//! Generated by spel-client-gen from IDL v0.1.0.
//! DO NOT EDIT — regenerate from IDL instead.

use std::str::FromStr;
use anyhow::{anyhow, Context};
use sequencer_service_rpc::RpcClient as _;
use nssa::{
    AccountId,
    ProgramId, PublicTransaction,
    public_transaction::{Message, WitnessSet},
};
// use spel_framework_core::prelude::AccountId;
use borsh::{BorshSerialize, BorshDeserialize};
use nssa::program::Program;
use serde::{Deserialize, Serialize};
use wallet::WalletCore;

/// Parse a hex string into ProgramId [u32; 8] (little-endian byte order).
pub fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {
    let s = s.trim_start_matches("0x");
    if s.len() != 64 {
        return Err(format!("program_id hex must be 64 chars, got {}", s.len()));
    }
    let bytes = hex::decode(s).map_err(|e| format!("invalid hex: {}", e))?;
    let mut pid = [0u32; 8];
    for (i, chunk) in bytes.chunks(4).enumerate() {
        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());
    }
    Ok(pid)
}

/// Compute PDA for the `counter` account.
pub fn compute_counter_pda(program_id: &ProgramId) -> AccountId {
    let seed_const_0 = spel_framework_core::pda::seed_from_str("register");
    println!("AA calling compute_pda, pid: {:?}, seeds: {:?}", program_id, seed_const_0);
    let account_id = spel_framework_core::pda::compute_pda(program_id, &[
        &seed_const_0,
    ]);

    AccountId::new(account_id.into_value())
    // AccountId::for_public_pda(program_id, &pda_seed)
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum MyCounterInstruction {
    Initialize,
    Register,
    GetRegisterState,
}

pub struct InitializeAccounts {
    pub counter: AccountId,
    pub owner: AccountId,
}

pub struct RegisterAccounts {
    pub counter: AccountId,
    pub owner: AccountId,
}

pub struct GetRegisterStateAccounts {
    pub counter: AccountId,
}

pub struct MyCounterClient<'w> {
    pub wallet: &'w WalletCore,
    pub program_id: ProgramId,
}

impl<'w> MyCounterClient<'w> {
    pub fn new(wallet: &'w WalletCore, program_id: ProgramId) -> Self {
        Self { wallet, program_id }
    }

    pub async fn initialize(
        &self,
        accounts: InitializeAccounts,
    ) -> Result<String, String> {
        let instruction = MyCounterInstruction::Initialize;
        let mut account_ids: Vec<AccountId> = vec![
            accounts.counter,
            accounts.owner,
        ];
        let signer_ids: Vec<AccountId> = vec![
            accounts.owner,
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    pub async fn register(
        &self,
        accounts: RegisterAccounts,
    ) -> Result<String, String> {
        let instruction = MyCounterInstruction::Register;
        let mut account_ids: Vec<AccountId> = vec![
            accounts.counter,
            accounts.owner,
        ];
        let signer_ids: Vec<AccountId> = vec![
            accounts.owner,
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    pub async fn get_register_state(
        &self,
        accounts: GetRegisterStateAccounts,
    ) -> Result<String, String> {
        let instruction = MyCounterInstruction::GetRegisterState;
        let mut account_ids: Vec<AccountId> = vec![
            accounts.counter,
        ];
        let signer_ids: Vec<AccountId> = vec![
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    /// Fetch and deserialize the `counter` account state.
    pub async fn fetch_counter<T: BorshDeserialize>(
        &self,
    ) -> Result<T, String> {
        println!("Fetching counter for {:?}", self.program_id);
        let account_id_0 = compute_counter_pda(&self.program_id);
        println!("account_id_0: {:?}", account_id_0);

        // Debug (only)
        let account_id = AccountId::from_str("D1zcrwMESt5xXWq6S6mAUCsGoA4AbWCCEevyxFDSWvhS").unwrap();
        println!("Fetching counter for {}", account_id);

        println!("account_id_0: {:?}", account_id_0);
        println!("account_id: {:?}", account_id);

        let account = self.wallet.sequencer_client
            .get_account(account_id_0).await
            .map_err(|e| format!("fetch counter: {}", e))?;
        T::try_from_slice(&account.data)
            .map_err(|e| format!("deserialize counter: {}", e))
    }
}

// Added

mod imt;
use crate::imt::{OracleMerkleTree, TREE_CAPACITY};
// use borsh::{BorshDeserialize, BorshSerialize};
use tiny_keccak::{Hasher, Keccak};

#[derive(Debug, Clone, BorshSerialize, BorshDeserialize)]
pub struct RegisterState {
    // /// The current count value.
    // pub count: u64,
    /// The owner
    pub owner: [u8; 32],
    pub mtree: OracleMerkleTree,
    // Note: with tree depth of 10, this is 32 * 1024 -> 32Kb so ok
    pub registered: [[u8; 32]; TREE_CAPACITY],
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {

    let program_path_ = std::env::args().into_iter().nth(1);

    println!("program path: {:?}", program_path_);
    let program_path = program_path_.ok_or(anyhow!("No args"))?;
    let program_bytecode = std::fs::read(program_path.clone())
        .context(format!("Error while reading: {}", program_path))?;
    let program = Program::new(program_bytecode.into())?;
    // println!("program: {:?}", program);
    let pid = program.id();
    println!("pid: {:?}", pid);

    let wallet_core = WalletCore::from_env()?;
    let client = MyCounterClient::new(&wallet_core, pid);
    // println!("client wallet: {:?}", client.wallet);

    let data = client.fetch_counter::<RegisterState>().await;
    println!("data registered 0: {:?}", data.unwrap().registered[0]);

    Ok(())
}