//! Auto-generated client for the oracle_register program.
//! Generated by spel-client-gen from IDL v0.1.0.
//! DO NOT EDIT — regenerate from IDL instead.

use sequencer_service_rpc::RpcClient as _;
use nssa::{
    AccountId, ProgramId, PublicTransaction,
    public_transaction::{Message, WitnessSet},
};
use borsh::BorshDeserialize;
use serde::{Deserialize, Serialize};
use wallet::WalletCore;

/// Parse a hex string into ProgramId [u32; 8] (little-endian byte order).
pub fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {
    let s = s.trim_start_matches("0x");
    if s.len() != 64 {
        return Err(format!("program_id hex must be 64 chars, got {}", s.len()));
    }
    let bytes = hex::decode(s).map_err(|e| format!("invalid hex: {}", e))?;
    let mut pid = [0u32; 8];
    for (i, chunk) in bytes.chunks(4).enumerate() {
        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());
    }
    Ok(pid)
}

/// Compute PDA for the `register` account.
pub fn compute_register_pda(program_id: &ProgramId) -> AccountId {
    let seed_const_0 = spel_framework_core::pda::seed_from_str("register");
    spel_framework_core::pda::compute_pda(program_id, &[
        &seed_const_0,
    ])
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum OracleRegisterInstruction {
    Initialize {
        token_program_id: program_id,
    },
    Register {
        oracle_key: [u8; 32],
        pda_seed: [u8; 32],
    },
}

pub struct InitializeAccounts {
    pub register: AccountId,
    pub owner: AccountId,
}

pub struct RegisterAccounts {
    pub register: AccountId,
    pub from: AccountId,
    pub to: AccountId,
    pub token_def_account: AccountId,
}

pub struct OracleRegisterClient<'w> {
    pub wallet: &'w WalletCore,
    pub program_id: ProgramId,
}

impl<'w> OracleRegisterClient<'w> {
    pub fn new(wallet: &'w WalletCore, program_id: ProgramId) -> Self {
        Self { wallet, program_id }
    }

    pub async fn initialize(
        &self,
        accounts: InitializeAccounts,
        token_program_id: program_id,
    ) -> Result<String, String> {
        let instruction = OracleRegisterInstruction::Initialize {
            token_program_id,
        };
        let mut account_ids: Vec<AccountId> = vec![
            accounts.register,
            accounts.owner,
        ];
        let signer_ids: Vec<AccountId> = vec![
            accounts.owner,
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    pub async fn register(
        &self,
        accounts: RegisterAccounts,
        oracle_key: [u8; 32],
        pda_seed: [u8; 32],
    ) -> Result<String, String> {
        let instruction = OracleRegisterInstruction::Register {
            oracle_key,
            pda_seed,
        };
        let mut account_ids: Vec<AccountId> = vec![
            accounts.register,
            accounts.from,
            accounts.to,
            accounts.token_def_account,
        ];
        let signer_ids: Vec<AccountId> = vec![
            accounts.from,
        ];
        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await
            .map_err(|e| format!("nonces: {}", e))?;
        let mut signing_keys = Vec::new();
        for sid in &signer_ids {
            let key = self.wallet
                .get_account_public_signing_key(*sid)
                .ok_or_else(|| format!("signing key not found for {}", sid))?;
            signing_keys.push(key);
        }
        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)
            .map_err(|e| format!("message: {:?}", e))?;
        let witness_set = WitnessSet::for_message(&message, &signing_keys);
        let tx = PublicTransaction::new(message, witness_set);
        let response = self.wallet.sequencer_client.send_transaction(common::transaction::LeeTransaction::Public(tx)).await
            .map_err(|e| format!("submit: {}", e))?;
        Ok(hex::encode(response.0))
    }

    /// Fetch and deserialize the `register` account state.
    pub async fn fetch_register<T: BorshDeserialize>(
        &self,
    ) -> Result<T, String> {
        let account_id = compute_register_pda(&self.program_id);
        let account = self.wallet.sequencer_client
            .get_account(account_id).await
            .map_err(|e| format!("fetch register: {}", e))?;
        T::try_from_slice(&account.data)
            .map_err(|e| format!("deserialize register: {}", e))
    }
}
