[package]
name = "indexer"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
clap = { features = ["derive", "env", "std"], version = "4.6.6" }
futures = { default-features = false, version = "0.3.34" }
hex = "0.4.3"
sha2 = "0.11.0"
reqwest = { features = ["json", "rustls-tls"], workspace = true }
tokio = { default-features = false, features = [
    "io-std",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
], version = "1.53.1" }
tracing = { workspace = true }
tracing-subscriber = { features = ["env-filter"], version = "0.3.23" }
anyhow = { workspace = true }
# internal
common =  { path = "../common" }
oracle_register_client = { path = "../../oracle_register_client" }
oracle_prices_client = { path = "../../oracle_prices_client" }
prost = "0.14.4" # grpc
# logos
lb-common-http-client = { workspace = true }
lb-core = { workspace = true }
logos-blockchain-zone-sdk = { path = "../logos-blockchain/zone-sdk" }
# contract
spel-framework = { git = "https://github.com/logos-co/spel.git", tag = "v0.6.0" }
wallet = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }

[build-dependencies]
prost-build = "0.14.4"
