[package]
name = "oracle_register_client"
version = "0.1.0"
edition = "2024"

[dependencies]
# spel-framework = { git = "https://github.com/logos-co/spel.git", branch = "main" }
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee_core" }
# risc0-zkvm = { version = "=3.0.5", features = ["std", "getrandom"] }
# oracle_register_core = { path = "../../oracle_register_core" }
serde = { version = "1.0", features = ["derive"] }
borsh = { version = "1.5", features = ["derive"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }


nssa        = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee" }
common      = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
sequencer_service_rpc = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", features = ["client"] }
wallet      = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0" }
hex         = "0.4"
spel-framework = { git = "https://github.com/logos-co/spel.git", tag = "v0.6.0" }
spel-framework-core = { git = "https://github.com/logos-co/spel.git", tag = "v0.6.0" }
tokio       = { version = "1", features = ["rt-multi-thread"] }
anyhow = "1.0.104"
